version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
        name: Build UI
        command: |
          yarn
          npm run build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Build Binaries
        command: |
          npm i -g pkg
          pkg --version
          chmod +x build/package-bin.sh
          cd build && sudo ./package-bin.sh


