version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: 
          name: Install Dependencies
          command: |
            yarn
            cd client && yarn
            cd ../server && yarn

      - run:
          name: Build Electron
          command: yarn build

      - run:
          name: Build Binaries
          command: |
            sudo npm i -g pkg
            pkg --version
            chmod +x build/package-bin.sh
            cd build && sudo ./package-bin.sh

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      - store_artifacts:
          path: build/out/zip
          destination: zip



