version: 2.1

executors:
  node-x86:
    docker:
      - image: circleci/node:8.12.0
    working_directory: /tmp/repo

jobs:
  prepare:
    executor: node-x86

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-client-{{ checksum "client/package.json" }}
          - v1-dependencies-server-{{ checksum "server/package.json" }}

      - run:
          name: Set Version
          command: yarn version --no-git-tag-version --new-version 1.0.$CIRCLE_BUILD_NUM

      - run: 
          name: Install Dependencies
          command: |
            cd client && yarn
            cd ../server && yarn 
            
      - run:
          name: Build client
          command: |
            cd client
            yarn run build
            zip -r dist dist
      
      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "*.*"
            - "*/**"    

      - save_cache:
          name: Save Client Cache
          paths:
            - client/node_modules
          key: v1-dependencies-client-{{ checksum "client/package.json" }}

      - save_cache:
          name: Save Server Cache
          paths:
            - server/node_modules
          key: v1-dependencies-server-{{ checksum "server/package.json" }}

      # - store_artifacts:
      #     name: Store Client JS
      #     path: client/dist.zip
      #     destination: client.zip

  build-electron:
    executor: node-x86
    
    steps:
      - attach_workspace:
          at: /tmp/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Electron
          command: |
            yarn && yarn build
            cd build/out/electron
            # mkdir zip
            # mv *.zip zip

      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # - store_artifacts:
      #     name: Store Electorn Build
      #     path: build/out/electron/zip
      #     destination: electron

      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "build/out/electron/*.zip" 

  build-server:
    executor: node-x86
    
    steps:
      - attach_workspace:
          at: /tmp/repo

      - run:
          name: Build Binaries
          command: |
            sudo npm i -g pkg
            pkg --version
            chmod +x build/server-binaries.sh
            cd build && sudo ./server-binaries.sh

      # - store_artifacts:
      #     name: Store Server Binaries
      #     path: build/out/zip
      #     destination: server

      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "build/out/server/*.zip" 

  publish:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: /tmp/repo
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION="1.0.$CIRCLE_BUILD_NUM"
            echo "Release version ${VERSION}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} /tmp/repo/build/out/


workflows:
  version: 2.1
  build:
    jobs:
      - prepare
      - build-electron:
          requires:
            - prepare
      - build-server:
          requires:
            - prepare
      - publish:
          requires:
            - build-electron
            - build-server