version: 2.1

executors:
  node-x86:
    docker:
      - image: circleci/node:8.12.0
    working_directory: /tmp/repo

jobs:
  prepare:
    executor: node-x86

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-client-{{ checksum "client/package.json" }}
          - v1-dependencies-server-{{ checksum "server/package.json" }}

      - run:
          name: Set Version
          command: yarn version --no-git-tag-version --new-version 1.0.${CIRCLE_BUILD_NUM}

      - run: 
          name: Install Dependencies
          command: |
            cd client && yarn
            cd ../server && yarn 
            
      - run:
          name: Build client
          command: |
            cd client
            yarn run build
            zip -r dist dist
      
      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "*.*"
            - "*/**"    

      - save_cache:
          name: Save Client Cache
          paths:
            - client/node_modules
          key: v1-dependencies-client-{{ checksum "client/package.json" }}

      - save_cache:
          name: Save Server Cache
          paths:
            - server/node_modules
          key: v1-dependencies-server-{{ checksum "server/package.json" }}

  build-electron:
    executor: node-x86
    
    steps:
      - attach_workspace:
          at: /tmp/repo

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Build Electron
          command: |
            yarn && yarn build
            cd build/out/electron

      - save_cache:
          name: Save Cache
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "build/out/electron/*.zip" 

  build-server:
    executor: node-x86
    
    steps:
      - attach_workspace:
          at: /tmp/repo

      - run:
          name: Build Binaries
          command: |
            sudo npm i -g pkg
            pkg --version
            chmod +x build/server-binaries.sh
            cd build && sudo ./server-binaries.sh

      - persist_to_workspace:
          root: /tmp/repo
          paths: 
            - "build/out/server/*.zip" 

  publish:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/repo
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION="1.0.${CIRCLE_BUILD_NUM}"
            echo "Release version ${VERSION}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} /tmp/repo/build/out/server
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} /tmp/repo/build/out/electron


workflows:
  version: 2.1
  build:
    jobs:
      - prepare
      - build-electron:
          requires:
            - prepare
      - build-server:
          requires:
            - prepare
      - publish:
          requires:
            - build-electron
            - build-server